version: 2.1

jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Deploy Over SSH
          #command: ssh $SSH_USER@$SSH_HOST 'sudo salt-call --local state.apply'
          command:
            - ssh $SSH_USER@$SSH_HOST 'ls -la'

workflows:
  main:
    jobs:
      - deploy
