version: 2.1

jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: ssh $SSH_USER@$SSH_HOST 'sudo salt-call --local state.apply'

workflows:
  main:
    jobs:
      - deploy
