version: 2.1

jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "9f:6d:a9:1d:01:7a:dc:51:cf:2c:98:d3:7d:5c:99:28"
      - checkout
      - run:
          name: Deploy Over SSH
          command: ssh $SSH_ROOT_USER@$SSH_ROOT_HOST 'salt-call --local state.apply'

workflows:
  main:
    jobs:
      - deploy
